-- Generated by drizzle-kit generate from live v1 snapshot -> src/db/schema.ts.
-- Kit also emitted table-rebuild SQL that dropped STRICT; only ADD COLUMN statements are applied.
ALTER TABLE `requests` ADD `locality_bias` real;
ALTER TABLE `requests` ADD `transport` text;
ALTER TABLE `requests` ADD `boundary` text;
ALTER TABLE `requests` ADD `saturation` integer;
ALTER TABLE `requests` ADD `selection_reason_code` text;
ALTER TABLE `requests` ADD `selection_reason_detail` text;
