-- Generated by drizzle-kit generate from live v2 snapshot -> src/db/schema.ts.
-- Kit also emitted STRICT-dropping table rebuilds; only ADD COLUMN is applied.
ALTER TABLE `requests` ADD `cost_source` text;
