"""Ryzen AI Software 1.8.0 operator coverage.

Source: https://ryzenai.docs.amd.com/en/latest/ops_support.html
A "Y" in the AMD table is treated as coverage for that quantization. Specific
configurations may still fail compilation on hardware; this table is the
static probe, not a substitute for vitisai_ep_report.json.
"""

from __future__ import annotations

# Operators marked Y under BF16 for CNN/NLP models.
BF16 = frozenset(
    {
        "Abs",
        "Add",
        "And",
        "ArgMax",
        "ArgMin",
        "AveragePool",
        "BatchNormalization",
        "BitShift",
        "BitwiseAnd",
        "BitwiseNot",
        "BitwiseOr",
        "BitwiseXor",
        "Cast",
        "Ceil",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "ConvTranspose",
        "CumSum",
        "DepthToSpace",
        "Div",
        "Einsum",
        "Equal",
        "Erf",
        "Exp",
        "Expand",
        "Flatten",
        "Floor",
        "Gather",
        "GatherElements",
        "Gemm",
        "GlobalAveragePool",
        "Greater",
        "GridSample",
        "GroupConv",
        "Identity",
        "InstanceNormalization",
        "LSTM",
        "Less",
        "Log",
        "MatMul",
        "Max",
        "MaxPool",
        "Min",
        "Mod",
        "Mul",
        "Neg",
        "Not",
        "Or",
        "Pad",
        "Pow",
        "Reciprocal",
        "ReduceMax",
        "ReduceMean",
        "ReduceMin",
        "ReduceSum",
        "Reshape",
        "Resize",
        "Round",
        "ScatterND",
        "Shape",
        "Sigmoid",
        "Sign",
        "Sin",
        "Size",
        "Slice",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "Tile",
        "Transpose",
        "Unsqueeze",
        "Upsample",
        "Where",
        "Xor",
    }
)

# Union of A16W8 / A8W8 / XINT8 Y columns.
INT8 = frozenset(
    {
        "Abs",
        "Add",
        "And",
        "ArgMax",
        "ArgMin",
        "AveragePool",
        "BatchNormalization",
        "BitShift",
        "BitwiseAnd",
        "BitwiseNot",
        "BitwiseOr",
        "BitwiseXor",
        "Cast",
        "Ceil",
        "Celu",
        "Clip",
        "Concat",
        "Constant",
        "ConstantOfShape",
        "Conv",
        "ConvTranspose",
        "Cos",
        "CumSum",
        "DepthToSpace",
        "DequantizeLinear",
        "Div",
        "Elu",
        "Equal",
        "Erf",
        "Exp",
        "Expand",
        "Flatten",
        "Floor",
        "Gather",
        "GatherElements",
        "Gelu",
        "Gemm",
        "GlobalAveragePool",
        "GlobalMaxPool",
        "Greater",
        "GreaterOrEqual",
        "GroupNormalization",
        "HardSigmoid",
        "HardSwish",
        "Identity",
        "InstanceNormalization",
        "LayerNormalization",
        "LeakyRelu",
        "Less",
        "LessOrEqual",
        "Log",
        "MatMul",
        "Max",
        "MaxPool",
        "Min",
        "Mish",
        "Mul",
        "Neg",
        "Or",
        "Pad",
        "Pow",
        "QLinearConv",
        "QLinearMatMul",
        "QuantizeLinear",
        "Range",
        "Reciprocal",
        "ReduceMax",
        "ReduceMean",
        "ReduceMin",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Resize",
        "Round",
        "STFT",
        "Shape",
        "Shrink",
        "Sigmoid",
        "Sign",
        "Sin",
        "Slice",
        "Softmax",
        "Softsign",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tanh",
        "ThresholdedRelu",
        "Tile",
        "TopK",
        "Transpose",
        "Unsqueeze",
        "Upsample",
        "Where",
    }
)

# Used by ModernBERT-large + DecisionModel head. Absent from the BF16 column.
LAYA_BF16_GAPS = ("Softmax", "Gelu", "LayerNormalization")


def supported_ops(precision: str) -> frozenset[str]:
    if precision == "int8":
        return INT8
    return BF16
